In [1]:
import numpy as np

np.random.seed(1)

def relu(x):
    return (x > 0) * x # returns x if x > 0
                       # return 0 otherwise

def relu2deriv(output):
    return output>0 # returns 1 for input > 0
                    # return 0 otherwise

streetlights = np.array( [[ 1, 0, 1 ],
                          [ 0, 1, 1 ],
                          [ 0, 0, 1 ],
                          [ 1, 1, 1 ]] )

walk_vs_stop = np.array([[ 1, 1, 0, 0]]).T

alpha = 0.2 # 学習率
hidden_size = 4

weights_0_1 = 2*np.random.random((3,hidden_size)) - 1
weights_1_2 = 2*np.random.random((hidden_size,1)) - 1

In [2]:
weights_0_1

array([[-0.16595599,  0.44064899, -0.99977125, -0.39533485],
       [-0.70648822, -0.81532281, -0.62747958, -0.30887855],
       [-0.20646505,  0.07763347, -0.16161097,  0.370439  ]])

In [3]:
weights_1_2

array([[-0.5910955 ],
       [ 0.75623487],
       [-0.94522481],
       [ 0.34093502]])

In [4]:
layer_0 = streetlights[0:1]
layer_0 

array([[1, 0, 1]])

In [5]:
layer_1 = relu(np.dot(layer_0,weights_0_1))
layer_1 

array([[-0.        ,  0.51828245, -0.        , -0.        ]])

In [6]:
layer_2 = np.dot(layer_1,weights_1_2)
layer_2 

array([[0.39194327]])

In [9]:
layer_2_error = 0
layer_2_error += np.sum((layer_2 - walk_vs_stop[0:1]) ** 2)
layer_2_error

0.3697329913497495

In [10]:
layer_2_delta = (layer_2 - walk_vs_stop[0:1])
layer_2_delta

array([[-0.60805673]])

In [11]:
layer_1_delta=layer_2_delta.dot(weights_1_2.T)*relu2deriv(layer_1)
layer_1_delta

array([[ 0.        , -0.45983371,  0.        , -0.        ]])